---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: karatcdb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/karatcdb-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: karatcdb-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: karatcdb-pv
---
kind: Service
apiVersion: v1
metadata:
  name: karatcdb-svc
spec:
  selector:
    app: karatcdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karatcdb-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 5
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: karatcdb
  template:
    metadata:
      labels:
        app: karatcdb
    spec:
      containers:
        - name: karatcdb-psql
          image: postgis/postgis:11-2.5
          env:
            - name: POSTGRES_DB
              value: karatcdb
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: karatcdb-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: karatcdb-volume
          persistentVolumeClaim:
            claimName: karatcdb-pvc
