---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: karatc-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/karatc-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: karatc-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: karatc-pv
---
kind: Service
apiVersion: v1
metadata:
  name: karatcweb-svc
spec:
  type: NodePort
  selector:
    app: karatcweb
  ports:
    - name: karat-c
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30200
---
kind: Service
apiVersion: v1
metadata:
  name: karatcds-svc
spec:
  selector:
    app: karatcweb
  ports:
    - name: command-port
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: backend-port
      protocol: TCP
      port: 8002
      targetPort: 8002
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: karatc-cm
data:
  karat-c.conf: |
          Listen 80
          WSGIPythonPath /opt/karat/karat_c
          WSGIPassAuthorization On

          <VirtualHost *:80>
              WSGIScriptAlias / /opt/karat/karat_c/karat_c/wsgi.py

              <Directory />
                  Options FollowSymLinks
                  AllowOverride None
                  Require all granted
              </Directory>

              <Directory /opt/karat/karat_c/karat_c >
                  <Files wsgi.py>
                      Require all granted
                  </Files>
              </Directory>

              <Directory /opt/karat/karat_c/media >
                  LimitRequestBody 6000000
              </Directory>
  
              Alias /static "/opt/karat/karat_c/static"
  
              ErrorLog /dev/stdout
              TransferLog /dev/stdout
          </VirtualHost>
  DB_NAME: "karatcdb"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_HOST: "karatcdb-svc"
  DB_PORT: "5432"
  TZ: "Europe/Moscow"
  LANG: "ru_RU.UTF-8"
  APACHE_RUN_USER: "root"
  APACHE_RUN_GROUP: "root"
  VIRTUAL_HOST: "karat-c.test"
  KARAT_TYPE: "karat_c"
  FRONTEND_PORT: "1111"
  BACKEND_PORT: "8001"
  COMMAND_PORT: "8002"
  COMMAND_PORT_C: "8002"
  CHAT_HOST: "192.168.100.245"
  CHAT_PORT: "8003"
  MONITOR_PORT: "2222"
  CURRENT_COMPLEX_UID: "f73a5cd4-ddc3-4e69-9355-9d2f5d6a79c3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karatc-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 5
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: karatcweb
  template:
    metadata:
      labels:
        app: karatcweb
    spec:
      containers:
        - name: karat-c
          image: django-app:v1
          args: ["with_init", "apache2ctl", "-D", "FOREGROUND"]
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: karatc-cm
          imagePullPolicy: Never
          volumeMounts:
            - name: karat-c
              mountPath: /etc/apache2/sites-available/000-default.conf
              subPath: 000-default.conf
              readOnly: true
            - name: karat-static
              mountPath: /opt/karat/karat_c/static

        - name: messages-worker
          image: django-app:v1
          args: ["python3", "./karat_c/manage.py", "runworker"]
          ports:
            - containerPort: 8001
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: karatc-cm
          imagePullPolicy: Never

        - name: warehouse-order 
          image: django-app:v1
          args: ["python3", "./karat_c/service.py", "warehouse_order"]
          envFrom:
            - configMapRef:
                name: karatc-cm
          imagePullPolicy: Never

      volumes:
        - name: karat-static
          persistentVolumeClaim:
            claimName: karatc-pvc

        - name: karat-c
          configMap:
            name: karatc-cm
            items:
              - key: karat-c.conf
                path: 000-default.conf    
