---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxxxxx
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        args:
        - "aaaaaa"
        ports:
        - containerPort: 80
